-- FutonHUB Supabase Base Segura v4
-- Ejecutar en Supabase > SQL Editor.
-- Objetivo: usuarios simples (admin/worker), logs invisibles para workers,
-- snapshots de respaldo y bloqueos online para trabajo simultáneo.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null unique,
    display_name text,
    role text not null check (role in ('admin', 'worker')) default 'worker',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.devices (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.profiles(id) on delete set null,
    machine_name text not null,
    device_label text,
    role text check (role in ('admin', 'worker', 'standalone')) default 'worker',
    active boolean not null default true,
    last_seen_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
    id bigint generated by default as identity primary key,
    role text not null check (role in ('admin', 'worker')),
    module text not null,
    can_view boolean not null default false,
    can_create boolean not null default false,
    can_update boolean not null default false,
    can_delete boolean not null default false,
    can_execute boolean not null default false,
    unique(role, module)
);

create table if not exists public.system_locks (
    id uuid primary key default gen_random_uuid(),
    operation_key text not null unique,
    locked_by uuid references public.profiles(id) on delete set null,
    locked_by_machine text,
    locked_at timestamptz not null default now(),
    expires_at timestamptz not null,
    status text not null check (status in ('running', 'released', 'failed', 'expired')) default 'running',
    details text
);

create table if not exists public.entity_locks (
    id uuid primary key default gen_random_uuid(),
    entity_type text not null,
    entity_id text not null,
    locked_by uuid references public.profiles(id) on delete set null,
    locked_by_machine text,
    locked_at timestamptz not null default now(),
    expires_at timestamptz not null,
    status text not null check (status in ('running', 'released', 'expired')) default 'running',
    details text,
    unique(entity_type, entity_id)
);

create table if not exists public.audit_logs (
    id uuid primary key default gen_random_uuid(),
    operation_id text not null,
    created_at timestamptz not null default now(),
    user_id uuid references public.profiles(id) on delete set null,
    user_email text,
    role text,
    device_id uuid references public.devices(id) on delete set null,
    machine_name text,
    module text not null,
    action text not null,
    entity_type text,
    entity_id text,
    severity text not null check (severity in ('INFO', 'WARNING', 'ERROR', 'CRITICAL')) default 'INFO',
    status text not null,
    before_data jsonb,
    after_data jsonb,
    message text,
    error_detail text
);

create table if not exists public.operation_snapshots (
    id uuid primary key default gen_random_uuid(),
    operation_id text not null,
    created_at timestamptz not null default now(),
    user_id uuid references public.profiles(id) on delete set null,
    module text not null,
    action text not null,
    entity_type text not null,
    entity_id text not null,
    before_data jsonb not null,
    reason text
);

create table if not exists public.notifications (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    user_id uuid references public.profiles(id) on delete cascade,
    target_role text check (target_role in ('admin', 'worker')),
    title text not null,
    body text,
    severity text not null check (severity in ('INFO', 'WARNING', 'ERROR', 'CRITICAL')) default 'INFO',
    read_at timestamptz
);

-- Permisos base. Los workers trabajan, pero no ven sala de máquinas.
insert into public.role_permissions(role, module, can_view, can_create, can_update, can_delete, can_execute) values
('admin','security',true,true,true,true,true),
('admin','logs',true,true,true,true,true),
('admin','backups',true,true,true,true,true),
('admin','restore',true,true,true,true,true),
('admin','users',true,true,true,true,true),
('admin','settings',true,true,true,true,true),
('admin','woocommerce_publish',true,true,true,false,true),
('admin','inventory',true,true,true,true,true),
('admin','price_proposals',true,true,true,true,true),
('admin','cost',true,true,true,false,true),
('admin','cost_pedido',true,true,true,false,true),
('worker','inventory',true,true,true,false,true),
('worker','price_proposals',true,true,true,false,true),
('worker','cost',true,true,true,false,true),
('worker','cost_pedido',true,true,true,false,true),
('worker','products_read',true,false,false,false,false),
('worker','logs',false,false,false,false,false),
('worker','backups',false,false,false,false,false),
('worker','restore',false,false,false,false,false),
('worker','security',false,false,false,false,false)
on conflict(role, module) do update set
    can_view = excluded.can_view,
    can_create = excluded.can_create,
    can_update = excluded.can_update,
    can_delete = excluded.can_delete,
    can_execute = excluded.can_execute;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select role from public.profiles where id = auth.uid() and active = true
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(public.current_user_role() = 'admin', false)
$$;

alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.role_permissions enable row level security;
alter table public.system_locks enable row level security;
alter table public.entity_locks enable row level security;
alter table public.audit_logs enable row level security;
alter table public.operation_snapshots enable row level security;
alter table public.notifications enable row level security;

-- Limpieza para re-ejecutar este script sin acumular políticas duplicadas.
drop policy if exists "profiles_select_self_or_admin" on public.profiles;
drop policy if exists "profiles_admin_all" on public.profiles;
drop policy if exists "devices_self_or_admin" on public.devices;
drop policy if exists "devices_insert_self" on public.devices;
drop policy if exists "role_permissions_read_authenticated" on public.role_permissions;
drop policy if exists "locks_admin_all" on public.system_locks;
drop policy if exists "locks_authenticated_read" on public.system_locks;
drop policy if exists "entity_locks_authenticated_read" on public.entity_locks;
drop policy if exists "entity_locks_authenticated_write" on public.entity_locks;
drop policy if exists "audit_admin_read" on public.audit_logs;
drop policy if exists "audit_authenticated_insert" on public.audit_logs;
drop policy if exists "snapshots_admin_read" on public.operation_snapshots;
drop policy if exists "snapshots_authenticated_insert" on public.operation_snapshots;
drop policy if exists "notifications_own_or_admin" on public.notifications;
drop policy if exists "notifications_insert_admin" on public.notifications;

create policy "profiles_select_self_or_admin" on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy "profiles_admin_all" on public.profiles
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "devices_self_or_admin" on public.devices
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "devices_insert_self" on public.devices
for insert to authenticated
with check (user_id = auth.uid() or public.is_admin());

create policy "role_permissions_read_authenticated" on public.role_permissions
for select to authenticated
using (true);

create policy "locks_authenticated_read" on public.system_locks
for select to authenticated
using (true);

create policy "locks_admin_all" on public.system_locks
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "entity_locks_authenticated_read" on public.entity_locks
for select to authenticated
using (true);

create policy "entity_locks_authenticated_write" on public.entity_locks
for insert to authenticated
with check (locked_by = auth.uid() or public.is_admin());

create policy "audit_admin_read" on public.audit_logs
for select to authenticated
using (public.is_admin());

create policy "audit_authenticated_insert" on public.audit_logs
for insert to authenticated
with check (user_id = auth.uid() or public.is_admin());

create policy "snapshots_admin_read" on public.operation_snapshots
for select to authenticated
using (public.is_admin());

create policy "snapshots_authenticated_insert" on public.operation_snapshots
for insert to authenticated
with check (user_id = auth.uid() or public.is_admin());

create policy "notifications_own_or_admin" on public.notifications
for select to authenticated
using (user_id = auth.uid() or target_role = public.current_user_role() or public.is_admin());

create policy "notifications_insert_admin" on public.notifications
for insert to authenticated
with check (public.is_admin());
