#!/bin/bash
A=aaaaaaaa-0000-0000-0000-000000000001; W=bbbbbbbb-0000-0000-0000-000000000002; I=cccccccc-0000-0000-0000-000000000003; N=NONE
t(){ echo "### $1 | $2 uid=${3:0:4} | $4"; ./atk.sh "$2" "$3" "$4"; }
P1=11111111-1111-1111-1111-111111111111
echo "=== (a) price_change_proposals como worker"
for s in published approved publishing rolled_back; do t "a-$s" authenticated $W "UPDATE price_change_proposals SET status='$s' WHERE id='$P1';"; done
t a-reviewed_by authenticated $W "UPDATE price_change_proposals SET reviewed_by='$A', published_by='$A', reviewed_at=now(), published_at=now() WHERE id='$P1'; SELECT reviewed_by,published_by FROM price_change_proposals WHERE id='$P1';"
t a-source_row authenticated $W "UPDATE price_change_proposals SET source_row='{\"forged\":true}', new_price=0.01 WHERE id='$P1'; SELECT source_row,new_price FROM price_change_proposals WHERE id='$P1';"
t a-inactive authenticated $I "UPDATE price_change_proposals SET status='approved' WHERE id='$P1';"
t a-anon anon $N "UPDATE price_change_proposals SET status='approved' WHERE id='$P1';"
t a-delete-worker authenticated $W "DELETE FROM price_change_proposals WHERE id='$P1';"
echo "=== (b) inventory_items / business_constants / supplier_prices como worker"
t b-woo_id authenticated $W "UPDATE inventory_items SET woo_id=9999, woo_link_status='Enlazado' WHERE item_id=1; SELECT woo_id FROM inventory_items WHERE item_id=1;"
t b-costes authenticated $W "UPDATE inventory_items SET weighted_average_cost=0.01, primary_supplier_price='0.01', source_row='{}' WHERE item_id=1; SELECT weighted_average_cost FROM inventory_items WHERE item_id=1;"
t b-insert-inv authenticated $W "INSERT INTO inventory_items(item_id,name,woo_id) VALUES(77,'x',1001); SELECT count(*) FROM inventory_items WHERE woo_id=1001;"
t b-delete-inv authenticated $W "DELETE FROM inventory_items WHERE item_id=1; SELECT count(*) FROM inventory_items WHERE item_id=1;"
t b-bc-update authenticated $W "UPDATE business_constants SET value='0' WHERE key='PRICE_DROP_BLOCK_PERCENT'; SELECT value FROM business_constants;"
t b-bc-insert authenticated $W "INSERT INTO business_constants(key,value) VALUES('X','1');"
t b-bc-delete-worker authenticated $W "DELETE FROM business_constants WHERE key='PRICE_DROP_BLOCK_PERCENT'; SELECT count(*) FROM business_constants;"
t b-bc-delete-admin authenticated $A "DELETE FROM business_constants WHERE key='PRICE_DROP_BLOCK_PERCENT'; SELECT count(*) FROM business_constants;"
t b-sp-update authenticated $W "UPDATE supplier_prices SET price='0.01' WHERE item_id=1; SELECT price FROM supplier_prices;"
t b-sp-delete authenticated $W "DELETE FROM supplier_prices WHERE item_id=1; SELECT count(*) FROM supplier_prices;"
t b-inactive-update authenticated $I "UPDATE inventory_items SET name='h' WHERE item_id=1; SELECT name FROM inventory_items WHERE item_id=1;"
echo "=== (c) anon RPC"
t c-read_audit_logs-anon anon $N "SELECT * FROM futonhub_read_audit_logs('$A',10);"
t c-read_snapshots-anon anon $N "SELECT operation_id,before_data FROM futonhub_read_operation_snapshots('$A',10);"
t c-snapshot_by_op-anon anon $N "SELECT * FROM futonhub_read_snapshot_by_operation_id('$A','op-seed');"
t c-clean_order-anon anon $N "SELECT futonhub_clean_worker_simulated_order('$A','TEST_WORKER_ORDER'); SELECT count(*) FROM supplier_orders;"
t c-clean_inventory-anon anon $N "SELECT futonhub_clean_worker_simulated_inventory('$A',-900001); SELECT count(*) FROM inventory_items WHERE item_id=-900001;"
t c-clean_price-anon anon $N "SELECT futonhub_clean_worker_simulated_price_proposal('$A',-990001);"
t c-review_price-anon anon $N "SELECT * FROM futonhub_review_worker_simulated_price_proposal('$A',-990001,'approved','x');"
t c-read_audit_logs-worker-with-admin-uuid authenticated $W "SELECT count(*) FROM futonhub_read_audit_logs('$A',10);"
t c-read_audit_logs-inactive authenticated $I "SELECT count(*) FROM futonhub_read_audit_logs('$A',10);"
t c-read_audit_logs-worker-own authenticated $W "SELECT count(*) FROM futonhub_read_audit_logs('$W',10);"
t c-clean_order-worker authenticated $W "SELECT futonhub_clean_worker_simulated_order('$A','TEST_WORKER_ORDER');"
t c-snapshot_by_op-worker authenticated $W "SELECT count(*) FROM futonhub_read_snapshot_by_operation_id('$A','op-seed');"
t c-clean_price-anon-nouid anon $N "SELECT futonhub_clean_worker_simulated_price_proposal('$W',-990001);"
echo "=== (d) vistas como anon"
for v in v_inventory_component_search v_inventory_hub_search_exact v_inventory_hub_search_ranked; do t "d-$v" anon $N "SELECT count(*) FROM $v;"; done
t d-view-cols anon $N "SELECT result_name,result_woo_id,related_name FROM v_inventory_hub_search_ranked LIMIT 3;"
t d-base-anon anon $N "SELECT count(*) FROM inventory_items;"
t d-view-update anon $N "UPDATE v_inventory_hub_search_ranked SET result_name='x';"
echo "=== (e) INSERT falso audit_logs/snapshots"
t e-audit-forge authenticated $W "INSERT INTO audit_logs(operation_id,user_id,user_email,role,module,action,status) VALUES('forged','$A','admin@lab.test','admin','m','a','OK'); SELECT 'inserted';"
t e-snap-forge authenticated $W "INSERT INTO operation_snapshots(operation_id,user_id,module,action,entity_type,entity_id,before_data) VALUES('forged','$A','m','a','t','1','{}'); SELECT 'inserted';"
t e-audit-anon anon $N "INSERT INTO audit_logs(operation_id,module,action,status) VALUES('x','m','a','OK');"
t e-audit-inactive authenticated $I "INSERT INTO audit_logs(operation_id,user_id,module,action,status) VALUES('x','$A','m','a','OK'); SELECT 'inserted';"
t e-audit-uid-null authenticated NONE "INSERT INTO audit_logs(operation_id,module,action,status) VALUES('x','m','a','OK'); SELECT 'inserted';"
t e-audit-flood authenticated $W "INSERT INTO audit_logs(operation_id,module,action,status) SELECT 'f'||g,'m','a','OK' FROM generate_series(1,1000) g; SELECT count(*) FROM audit_logs;"
echo "=== (f) DELETE/UPDATE audit_logs/snapshots"
for r in "authenticated $W" "authenticated $A" "anon $N"; do set -- $r
 t "f-audit-update" $1 $2 "UPDATE audit_logs SET message='tampered'; SELECT count(*) FROM audit_logs WHERE message='tampered';"
 t "f-audit-delete" $1 $2 "DELETE FROM audit_logs; SELECT count(*) FROM audit_logs;"
 t "f-snap-update" $1 $2 "UPDATE operation_snapshots SET reason='t'; SELECT count(*) FROM operation_snapshots WHERE reason='t';"
 t "f-snap-delete" $1 $2 "DELETE FROM operation_snapshots; SELECT count(*) FROM operation_snapshots;"
done
t f-truncate-worker authenticated $W "TRUNCATE audit_logs; SELECT count(*) FROM audit_logs;"
t f-truncate-anon anon $N "TRUNCATE operation_snapshots;"
t f-select-worker authenticated $W "SELECT count(*) FROM audit_logs; SELECT count(*) FROM operation_snapshots;"
t f-select-admin authenticated $A "SELECT count(*) FROM audit_logs; SELECT count(*) FROM operation_snapshots;"
echo "=== (g) components / backups"
for tb in inventory_item_components inventory_stock_reset_backups; do
 t "g-$tb-select" authenticated $W "SELECT count(*) FROM $tb;"
 t "g-$tb-select-admin" authenticated $A "SELECT count(*) FROM $tb;"
 t "g-$tb-delete" authenticated $W "DELETE FROM $tb; SELECT count(*) FROM $tb;"
 t "g-$tb-update-admin" authenticated $A "UPDATE $tb SET quantity=0;" 
done
t g-components-insert authenticated $W "INSERT INTO inventory_item_components(parent_item_code,component_item_code) VALUES('A','B');"
t g-components-insert-admin authenticated $A "INSERT INTO inventory_item_components(parent_item_code,component_item_code) VALUES('A','B');"
t g-backups-insert authenticated $W "INSERT INTO inventory_stock_reset_backups(run_id,source_name,stock_field,item_id) VALUES(gen_random_uuid(),'s','f','1');"
t g-backups-truncate authenticated $W "TRUNCATE inventory_stock_reset_backups;"
t g-components-truncate-anon anon $N "TRUNCATE inventory_item_components;"
t g-view-worker authenticated $W "SELECT count(*) FROM v_inventory_component_search;"
t g-view-anon-components-leak anon $N "SELECT parent_item_code,component_item_code,quantity FROM v_inventory_component_search LIMIT 3;"
echo "=== (h) is_admin/has_role anon"
t h-is_admin-anon anon $N "SELECT is_admin(), is_worker_or_admin(), has_role(array['admin']), current_user_role();"
t h-is_admin-admin authenticated $A "SELECT is_admin(), is_worker_or_admin(), has_role(array['admin']), current_user_role();"
t h-inactive authenticated $I "SELECT is_admin(), is_worker_or_admin(), current_user_role();"
t h-has_role-probe-anon anon $N "SELECT has_role(array['worker']);"
echo "=== (i) profiles / devices"
t i-selfpromote authenticated $W "UPDATE profiles SET role='admin' WHERE id='$W'; SELECT role FROM profiles WHERE id='$W';"
t i-selfactivate authenticated $I "UPDATE profiles SET active=true WHERE id='$I'; SELECT active FROM profiles WHERE id='$I';"
t i-insert-profile authenticated $W "INSERT INTO profiles(id,email,role) VALUES('$W','x@y.z','admin');"
t i-insert-profile-new authenticated $W "INSERT INTO auth.users(id,email) VALUES(gen_random_uuid(),'q'); SELECT 1;"
t i-delete-profile authenticated $W "DELETE FROM profiles WHERE id='$A'; SELECT count(*) FROM profiles;"
t i-select-profiles-worker authenticated $W "SELECT count(*) FROM profiles;"
t i-profiles-anon anon $N "SELECT count(*) FROM profiles;"
t i-devices-insert-own authenticated $W "INSERT INTO devices(user_id,machine_name,role) VALUES('$W','pc1','admin'); SELECT 'inserted';"
echo "=== (k) devices user_id ajeno"
t k-devices-foreign authenticated $W "INSERT INTO devices(user_id,machine_name) VALUES('$A','pcX'); SELECT 'inserted';"
t k-devices-null-user authenticated $W "INSERT INTO devices(user_id,machine_name) VALUES(NULL,'pcX'); SELECT 'inserted';"
t k-devices-update authenticated $W "UPDATE devices SET active=false;"
t k-devices-inactive-own authenticated $I "INSERT INTO devices(user_id,machine_name) VALUES('$I','pcI'); SELECT 'inserted';"
echo "=== (j) locks directos"
t j-system_locks-insert-worker authenticated $W "INSERT INTO system_locks(operation_key,locked_by,expires_at) VALUES('k2','$W',now()+interval '1h'); SELECT 'inserted';"
t j-system_locks-update-worker authenticated $W "UPDATE system_locks SET status='released' WHERE operation_key='seedlock'; SELECT status FROM system_locks WHERE operation_key='seedlock';"
t j-system_locks-delete-worker authenticated $W "DELETE FROM system_locks WHERE operation_key='seedlock'; SELECT count(*) FROM system_locks;"
t j-system_locks-admin-direct authenticated $A "UPDATE system_locks SET status='released' WHERE operation_key='seedlock'; SELECT status FROM system_locks;"
t j-system_locks-read-worker authenticated $W "SELECT operation_key,locked_by FROM system_locks;"
t j-entity_locks-insert-own authenticated $W "INSERT INTO entity_locks(entity_type,entity_id,locked_by,expires_at) VALUES('t','1','$W',now()+interval '1h'); SELECT 'inserted';"
t j-entity_locks-insert-foreign authenticated $W "INSERT INTO entity_locks(entity_type,entity_id,locked_by,expires_at) VALUES('t','1','$A',now()+interval '1h'); SELECT 'inserted';"
t j-entity_locks-insert-null authenticated $W "INSERT INTO entity_locks(entity_type,entity_id,locked_by,expires_at) VALUES('t','1',NULL,now()+interval '1h'); SELECT 'inserted';"
t j-entity_locks-update authenticated $W "UPDATE entity_locks SET status='released';"
t j-entity_locks-delete authenticated $W "DELETE FROM entity_locks;"
echo "=== (l) uid nulo con rol authenticated"
t l-uid-null authenticated NONE "SELECT auth.uid() IS NULL, is_admin(), is_worker_or_admin(), current_user_role();"
t l-uid-null-update authenticated NONE "UPDATE inventory_items SET name='x' WHERE item_id=1; SELECT name FROM inventory_items WHERE item_id=1;"
t l-uid-null-select authenticated NONE "SELECT count(*) FROM inventory_items;"
t l-uid-null-rpc authenticated NONE "SELECT futonhub_acquire_system_lock('k','$A','m');"
t l-uid-null-readlogs authenticated NONE "SELECT count(*) FROM futonhub_read_audit_logs('$A',5);"
t l-uid-garbage authenticated "not-a-uuid" "SELECT is_admin();"
