-- Esquema VIVO reconstruido (solo SELECT via MCP Supabase, proyecto ozxbvclabemkqrfrinft, PG17.6 en prod).
-- Requiere 00_supabase_sim.sql aplicado antes (roles + auth).
CREATE TABLE public.profiles (
 id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
 email text NOT NULL UNIQUE, display_name text, role text NOT NULL DEFAULT 'worker',
 active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT profiles_role_check CHECK (role = ANY (ARRAY['admin','worker'])));
CREATE TABLE public.role_permissions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role text NOT NULL, module text NOT NULL,
 can_view boolean NOT NULL DEFAULT false, can_create boolean NOT NULL DEFAULT false, can_update boolean NOT NULL DEFAULT false,
 can_delete boolean NOT NULL DEFAULT false, can_execute boolean NOT NULL DEFAULT false,
 CONSTRAINT role_permissions_role_check CHECK (role = ANY (ARRAY['admin','worker'])), UNIQUE (role, module));
CREATE TABLE public.devices (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 machine_name text NOT NULL, device_label text, role text DEFAULT 'worker', active boolean NOT NULL DEFAULT true,
 last_seen_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT devices_role_check CHECK (role = ANY (ARRAY['admin','worker','standalone'])));
CREATE TABLE public.audit_logs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), operation_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
 user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, user_email text, role text,
 device_id uuid REFERENCES public.devices(id) ON DELETE SET NULL, machine_name text, module text NOT NULL, action text NOT NULL,
 entity_type text, entity_id text, severity text NOT NULL DEFAULT 'INFO', status text NOT NULL,
 before_data jsonb, after_data jsonb, message text, error_detail text,
 CONSTRAINT audit_logs_severity_check CHECK (severity = ANY (ARRAY['INFO','WARNING','ERROR','CRITICAL'])));
CREATE INDEX idx_audit_logs_operation_id ON public.audit_logs (operation_id);
CREATE TABLE public.operation_snapshots (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), operation_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
 user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, module text NOT NULL, action text NOT NULL,
 entity_type text NOT NULL, entity_id text NOT NULL, before_data jsonb NOT NULL, reason text);
CREATE INDEX idx_operation_snapshots_operation_id ON public.operation_snapshots (operation_id);
CREATE TABLE public.business_constants (
 key text PRIMARY KEY, value jsonb NOT NULL, value_type text NOT NULL DEFAULT 'number', module text NOT NULL DEFAULT 'cost',
 description text, updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.entity_locks (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text NOT NULL, entity_id text NOT NULL,
 locked_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, locked_by_machine text,
 locked_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'running', details text,
 UNIQUE (entity_type, entity_id), CONSTRAINT entity_locks_status_check CHECK (status = ANY (ARRAY['running','released','expired'])));
CREATE TABLE public.system_locks (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), operation_key text NOT NULL UNIQUE,
 locked_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, locked_by_machine text,
 locked_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'running', details text,
 CONSTRAINT system_locks_status_check CHECK (status = ANY (ARRAY['running','released','failed','expired'])));
CREATE TABLE public.heca_stock (
 normalized_code text NOT NULL, warehouse_code integer NOT NULL, item_code text NOT NULL,
 quantity numeric DEFAULT 0, quantity_requested numeric DEFAULT 0, quantity_reserved numeric DEFAULT 0, quantity_supplier_ordered numeric DEFAULT 0,
 imported_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 PRIMARY KEY (normalized_code, warehouse_code));
CREATE TABLE public.inventory_items (
 item_id bigint PRIMARY KEY, name text NOT NULL, cubic_meters numeric, rotation_c numeric, packages integer,
 primary_supplier_price text, pascal_price text, source text, family text, subgroup text, size text, materials text,
 commercial_status text DEFAULT 'Normal', is_pack boolean NOT NULL DEFAULT false, store_stock numeric, warehouse_stock numeric,
 heca_reference text, notes text, woo_item_kind text, woo_id bigint, woo_parent_id bigint, woo_sku text, woo_name text, woo_type text,
 woo_price text, woo_categories text, woo_link_status text DEFAULT 'Sin enlazar', woo_link_notes text, woo_synced_at timestamptz,
 order_calculated_price numeric, supplier_order_qty numeric, supplier_order_provider text, supplier_order_file text,
 supplier_order_updated_at timestamptz, weighted_average_cost numeric, weighted_average_cost_updated_at timestamptz,
 source_row jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 item_kind text DEFAULT 'simple', source_woo_id bigint, source_woo_sku text, base_item_code text, component_summary text, hub_item_code text,
 item_record_type text DEFAULT 'simple', catalog_description text, brand text, catalog_range text, dat_status text, dat_is_active boolean,
 size_raw text, inner_dimensions text, outer_dimensions text, dimensions_notes text, raw_catalog_notes text, composition_raw text,
 composition_summary text, catalog_source text, catalog_source_file text, catalog_synced_at timestamptz, catalog_review_status text,
 filter_family text, filter_group text, filter_size text, filter_gama text,
 CONSTRAINT inventory_items_item_kind_check CHECK (item_kind = ANY (ARRAY['simple','alias','woo_pack','manual_pack','component'])));
CREATE INDEX idx_inventory_items_base_item_code ON public.inventory_items (base_item_code);
CREATE INDEX idx_inventory_items_catalog_review_status ON public.inventory_items (catalog_review_status);
CREATE INDEX idx_inventory_items_catalog_source ON public.inventory_items (catalog_source);
CREATE INDEX idx_inventory_items_filter_hierarchy ON public.inventory_items (filter_family, filter_group, filter_size, filter_gama);
CREATE INDEX idx_inventory_items_heca_reference_lower ON public.inventory_items (lower(TRIM(BOTH FROM heca_reference)));
CREATE INDEX idx_inventory_items_hub_item_code ON public.inventory_items (hub_item_code);
CREATE INDEX idx_inventory_items_hub_item_code_lower ON public.inventory_items (lower(TRIM(BOTH FROM hub_item_code)));
CREATE INDEX idx_inventory_items_record_type ON public.inventory_items (item_record_type);
CREATE INDEX idx_inventory_items_woo_id ON public.inventory_items (woo_id);  -- NO unique (en vivo hay 5 woo_id duplicados)
CREATE INDEX idx_inventory_items_woo_sku_lower ON public.inventory_items (lower(TRIM(BOTH FROM woo_sku)));
CREATE TABLE public.inventory_change_history (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), item_id bigint NOT NULL REFERENCES public.inventory_items(item_id) ON DELETE CASCADE,
 item_name text, field text, field_name text, old_value text, new_value text, operation_id text, message text, notes text, source text,
 change_source text, action text, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(),
 created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL);
CREATE INDEX idx_inventory_change_history_field ON public.inventory_change_history (COALESCE(field, field_name));
CREATE INDEX idx_inventory_change_history_item_created ON public.inventory_change_history (item_id, created_at DESC);
CREATE INDEX idx_inventory_change_history_operation ON public.inventory_change_history (operation_id);
CREATE UNIQUE INDEX uq_inventory_change_history_operation_item_field ON public.inventory_change_history (operation_id, item_id, COALESCE(field, field_name, '')) WHERE operation_id IS NOT NULL;
CREATE TABLE public.inventory_item_components (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), parent_item_code text NOT NULL, parent_item_id bigint, parent_name text,
 component_item_code text NOT NULL, component_item_id bigint, component_name text, quantity numeric(12,3) NOT NULL DEFAULT 1,
 relation_type text NOT NULL DEFAULT 'component', source text NOT NULL DEFAULT 'woo_sync_v53', woo_id bigint, woo_parent_id bigint,
 woo_sku text, woo_name text, woo_type text, woo_categories text, notes text,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid,
 CONSTRAINT inventory_item_components_relation_type_check CHECK (relation_type = ANY (ARRAY['component','alias','related','derived_offer'])));
CREATE INDEX idx_inventory_item_components_component_code ON public.inventory_item_components (component_item_code);
CREATE INDEX idx_inventory_item_components_component_id ON public.inventory_item_components (component_item_id);
CREATE INDEX idx_inventory_item_components_component_lower ON public.inventory_item_components (lower(TRIM(BOTH FROM component_item_code)));
CREATE INDEX idx_inventory_item_components_parent_code ON public.inventory_item_components (parent_item_code);
CREATE INDEX idx_inventory_item_components_parent_lower ON public.inventory_item_components (lower(TRIM(BOTH FROM parent_item_code)));
CREATE INDEX idx_inventory_item_components_woo_id ON public.inventory_item_components (woo_id);
CREATE UNIQUE INDEX uq_inventory_item_components_parent_component_type_woo ON public.inventory_item_components (parent_item_code, component_item_code, relation_type, COALESCE(woo_id, 0::bigint));
CREATE TABLE public.inventory_stock_reset_backups (
 backup_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, run_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
 source_name text NOT NULL, stock_field text NOT NULL, excel_item_id text, item_id text NOT NULL, item_name text,
 old_store_stock numeric, old_warehouse_stock numeric, new_stock numeric);
CREATE TABLE public.notifications (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL DEFAULT now(),
 user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE, target_role text, title text NOT NULL, body text,
 severity text NOT NULL DEFAULT 'INFO', read_at timestamptz,
 CONSTRAINT notifications_severity_check CHECK (severity = ANY (ARRAY['INFO','WARNING','ERROR','CRITICAL'])),
 CONSTRAINT notifications_target_role_check CHECK (target_role = ANY (ARRAY['admin','worker'])));
CREATE TABLE public.price_change_proposals (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), local_id bigint, item_kind text NOT NULL, item_woo_id bigint NOT NULL, name text NOT NULL,
 old_price numeric, new_price numeric, delta numeric, notes text, status text NOT NULL DEFAULT 'pending',
 created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz, published_at timestamptz, error_message text,
 source_row jsonb NOT NULL DEFAULT '{}', local_sqlite_id bigint, published_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 CONSTRAINT price_change_proposals_status_check CHECK (status = ANY (ARRAY['pending','approved','publishing','rejected','published','rolled_back','error','cancelled'])));
CREATE UNIQUE INDEX idx_price_change_proposals_local_sqlite_id ON public.price_change_proposals (local_sqlite_id);
CREATE INDEX idx_price_change_proposals_published_by ON public.price_change_proposals (published_by);
CREATE INDEX idx_price_change_proposals_status ON public.price_change_proposals (status);
CREATE INDEX idx_price_change_proposals_status_published_at ON public.price_change_proposals (status, published_at DESC);
CREATE TABLE public.product_variations (
 woo_id bigint PRIMARY KEY, parent_woo_id bigint NOT NULL, parent_name text NOT NULL, sku text, status text, regular_price text, sale_price text,
 price text, stock_status text, stock_quantity numeric, attributes_json jsonb NOT NULL DEFAULT '[]', attributes_label text,
 raw_json jsonb NOT NULL DEFAULT '{}', synced_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(),
 updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL);
CREATE TABLE public.products (
 woo_id bigint PRIMARY KEY, name text NOT NULL, sku text, type text, status text, regular_price text, sale_price text, price text,
 stock_status text, stock_quantity numeric, categories_json jsonb NOT NULL DEFAULT '[]', raw_json jsonb NOT NULL DEFAULT '{}',
 synced_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL);
CREATE TABLE public.supplier_orders (
 order_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), local_order_id bigint, provider text NOT NULL, order_file text,
 status text NOT NULL DEFAULT 'Pendiente', total_items numeric DEFAULT 0, total_cost numeric DEFAULT 0, notes text,
 created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(), source_row jsonb NOT NULL DEFAULT '{}');
CREATE UNIQUE INDEX idx_supplier_orders_local_order_id ON public.supplier_orders (local_order_id);
CREATE INDEX idx_supplier_orders_provider_status ON public.supplier_orders (provider, status);
CREATE TABLE public.supplier_order_items (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid REFERENCES public.supplier_orders(order_id) ON DELETE CASCADE,
 local_id bigint, item_id bigint, item_code text, item_name text, quantity_ordered numeric DEFAULT 0, quantity_received numeric DEFAULT 0,
 unit_cost numeric DEFAULT 0, line_cost numeric DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(),
 source_row jsonb NOT NULL DEFAULT '{}', local_item_id bigint);
CREATE UNIQUE INDEX idx_supplier_order_items_local_item_id ON public.supplier_order_items (local_item_id);
CREATE TABLE public.supplier_prices (
 item_id bigint NOT NULL, supplier text NOT NULL, price text, currency text DEFAULT 'EUR', source text,
 updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
 PRIMARY KEY (item_id, supplier));

-- ===== FUNCIONES (copiadas de pg_get_functiondef) =====
CREATE OR REPLACE FUNCTION public.current_user_role() RETURNS text LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $f$
  select p.role from public.profiles p where p.id = auth.uid() and p.active = true limit 1; $f$;
CREATE OR REPLACE FUNCTION public.has_role(p_roles text[]) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $f$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.active = true and p.role = any(p_roles)) $f$;
CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $f$
  select coalesce(public.current_user_role() = 'admin', false) $f$;
CREATE OR REPLACE FUNCTION public.is_worker_or_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $f$
  select public.has_role(array['admin', 'worker']) $f$;

CREATE OR REPLACE FUNCTION public.futonhub_acquire_system_lock(p_operation_key text, p_user_id uuid, p_machine_name text, p_details text DEFAULT ''::text, p_ttl_minutes integer DEFAULT 15)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare
  v_profile public.profiles%rowtype; v_now timestamptz := now(); v_expires timestamptz; v_existing public.system_locks%rowtype;
begin
  if auth.uid() is null or p_user_id is null or p_user_id <> auth.uid() then
    raise exception 'FutonHUB lock: usuario autenticado no coincide con p_user_id';
  end if;
  select * into v_profile from public.profiles where id = auth.uid() and active = true limit 1;
  if v_profile.id is null or v_profile.role <> 'admin' then
    raise exception 'FutonHUB lock: solo admin activo puede bloquear operaciones criticas';
  end if;
  if coalesce(trim(p_operation_key), '') = '' then
    raise exception 'FutonHUB lock: operation_key vacio';
  end if;
  v_expires := v_now + make_interval(mins => greatest(1, least(coalesce(p_ttl_minutes, 15), 120)));
  select * into v_existing from public.system_locks where operation_key = p_operation_key for update;
  if found and v_existing.status = 'running' and v_existing.expires_at > v_now then
    return jsonb_build_object('acquired', false,'operation_key', v_existing.operation_key,'locked_by', v_existing.locked_by,
      'locked_by_machine', v_existing.locked_by_machine,'expires_at', v_existing.expires_at,'details', v_existing.details);
  end if;
  insert into public.system_locks(operation_key, locked_by, locked_by_machine, locked_at, expires_at, status, details)
  values (p_operation_key, v_profile.id, p_machine_name, v_now, v_expires, 'running', p_details)
  on conflict(operation_key) do update set locked_by = excluded.locked_by, locked_by_machine = excluded.locked_by_machine,
    locked_at = excluded.locked_at, expires_at = excluded.expires_at, status = 'running', details = excluded.details;
  return jsonb_build_object('acquired', true,'operation_key', p_operation_key,'locked_by', v_profile.id,
    'locked_by_machine', p_machine_name,'expires_at', v_expires,'details', p_details);
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_release_system_lock(p_operation_key text, p_user_id uuid, p_status text DEFAULT 'released'::text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_status text;
begin
  if auth.uid() is null or p_user_id is null or p_user_id <> auth.uid() then
    raise exception 'FutonHUB lock: usuario autenticado no coincide con p_user_id';
  end if;
  if not public.has_role(array['admin']) then
    raise exception 'FutonHUB lock: solo admin puede liberar operaciones criticas';
  end if;
  v_status := lower(coalesce(nullif(p_status, ''), 'released'));
  if v_status not in ('released', 'failed', 'expired') then v_status := 'released'; end if;
  update public.system_locks set status = v_status, expires_at = now()
   where operation_key = p_operation_key and locked_by = auth.uid();
  return jsonb_build_object('released', found,'operation_key', p_operation_key,'status', v_status);
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_clean_worker_simulated_inventory(p_user_id uuid, p_item_id bigint DEFAULT '-900001'::integer)
 RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_role text; v_exists bigint;
begin
    select role into v_role from public.profiles where id = p_user_id and active = true limit 1;
    if v_role is distinct from 'admin' then raise exception 'Solo admin puede limpiar inventario simulado worker.'; end if;
    if p_item_id is distinct from -900001 then raise exception 'Esta RPC solo puede limpiar TEST_WORKER_INVENTORY_ITEM.'; end if;
    select item_id into v_exists from public.inventory_items
    where item_id = p_item_id and name = 'TEST_WORKER_INVENTORY_ITEM' and coalesce(source_row->>'test', 'false') = 'true' limit 1;
    if v_exists is null then return false; end if;
    delete from public.inventory_items where item_id = p_item_id and name = 'TEST_WORKER_INVENTORY_ITEM' and coalesce(source_row->>'test', 'false') = 'true';
    return true;
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_clean_worker_simulated_order(p_user_id uuid, p_order_file text DEFAULT 'TEST_WORKER_ORDER'::text)
 RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_role text; v_order_id uuid;
begin
    select role into v_role from public.profiles where id = p_user_id and active = true limit 1;
    if v_role is distinct from 'admin' then raise exception 'Solo admin puede limpiar pedido simulado worker.'; end if;
    if p_order_file is distinct from 'TEST_WORKER_ORDER' then raise exception 'Esta RPC solo puede limpiar TEST_WORKER_ORDER.'; end if;
    select order_id into v_order_id from public.supplier_orders where order_file = p_order_file and coalesce(source_row->>'test', 'false') = 'true' limit 1;
    if v_order_id is null then return false; end if;
    delete from public.supplier_order_items where order_id = v_order_id;
    delete from public.supplier_orders where order_id = v_order_id;
    return true;
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_clean_worker_simulated_price_proposal(p_user_id uuid, p_item_woo_id bigint DEFAULT '-990001'::integer)
 RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_role text; v_deleted integer := 0;
begin
  select role into v_role from public.profiles where id = auth.uid() and active = true limit 1;
  if v_role <> 'admin' then raise exception 'Solo admin puede limpiar la propuesta de precio simulada'; end if;
  delete from public.price_change_proposals where item_woo_id = p_item_woo_id and item_kind = 'product'
    and (name = 'TEST_WORKER_PRICE_PROPOSAL' or source_row->>'test_name' = 'worker_simulated_price_proposal');
  get diagnostics v_deleted = row_count;
  return v_deleted > 0;
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_read_audit_logs(p_user_id uuid, p_limit integer DEFAULT 50)
 RETURNS TABLE(id uuid, created_at timestamptz, operation_id text, user_email text, role text, machine_name text, module text, action text, severity text, status text, entity_type text, entity_id text, message text, error_detail text)
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
begin
  if not exists (select 1 from public.profiles p where p.id = p_user_id and p.active = true and p.role = 'admin') then
    raise exception 'FutonHUB blackbox: solo admin puede leer audit_logs';
  end if;
  return query select a.id, a.created_at, a.operation_id, a.user_email, a.role, a.machine_name, a.module, a.action, a.severity, a.status, a.entity_type, a.entity_id, a.message, a.error_detail
  from public.audit_logs a order by a.created_at desc limit greatest(1, least(coalesce(p_limit, 50), 500));
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_read_operation_snapshots(p_user_id uuid, p_limit integer DEFAULT 50)
 RETURNS TABLE(id uuid, created_at timestamptz, operation_id text, user_id uuid, module text, action text, entity_type text, entity_id text, before_data jsonb, reason text)
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
begin
  if not exists (select 1 from public.profiles p where p.id = p_user_id and p.active = true and p.role = 'admin') then
    raise exception 'FutonHUB blackbox: solo admin puede leer operation_snapshots';
  end if;
  return query select s.id, s.created_at, s.operation_id, s.user_id, s.module, s.action, s.entity_type, s.entity_id, s.before_data, s.reason
  from public.operation_snapshots s order by s.created_at desc limit greatest(1, least(coalesce(p_limit, 50), 500));
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_read_snapshot_by_operation_id(p_user_id uuid, p_operation_id text)
 RETURNS TABLE(id uuid, created_at timestamptz, operation_id text, user_id uuid, module text, action text, entity_type text, entity_id text, before_data jsonb, reason text)
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
begin
  if not exists (select 1 from public.profiles p where p.id = p_user_id and p.id = auth.uid() and p.active = true and p.role = 'admin') then
    raise exception 'Solo admin puede leer snapshots para rollback';
  end if;
  return query select s.id, s.created_at, s.operation_id, s.user_id, s.module, s.action, s.entity_type, s.entity_id, s.before_data, s.reason
  from public.operation_snapshots s where s.operation_id = p_operation_id order by s.created_at desc limit 1;
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_review_worker_simulated_price_proposal(p_user_id uuid, p_item_woo_id bigint DEFAULT '-990001'::integer, p_decision text DEFAULT 'approved'::text, p_operation_id text DEFAULT NULL::text)
 RETURNS SETOF price_change_proposals LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_role text; v_decision text;
begin
  select role into v_role from public.profiles where id = auth.uid() and active = true limit 1;
  if v_role <> 'admin' then raise exception 'Solo admin puede revisar propuestas simuladas'; end if;
  v_decision := lower(trim(coalesce(p_decision, '')));
  if v_decision not in ('approved', 'rejected') then raise exception 'Decision invalida: %, use approved o rejected', p_decision; end if;
  return query
  update public.price_change_proposals p set status = v_decision, reviewed_by = auth.uid(), reviewed_at = now(),
    notes = coalesce(p.notes, '') || E'\n[TEST] Revision admin: ' || v_decision || '. No publicar en WooCommerce.',
    source_row = coalesce(p.source_row, '{}'::jsonb) || jsonb_build_object('review_test', true,'review_operation_id', p_operation_id,'review_decision', v_decision,'reviewed_by', auth.uid(),'reviewed_at', now())
  where p.item_woo_id = p_item_woo_id and p.item_kind = 'product' and (p.name = 'TEST_WORKER_PRICE_PROPOSAL' or p.source_row->>'test_name' = 'worker_simulated_price_proposal')
  returning p.*;
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_write_audit_log(p_operation_id text, p_user_id uuid, p_user_email text, p_role text, p_device_id uuid, p_machine_name text, p_module text, p_action text, p_status text, p_severity text DEFAULT 'INFO'::text, p_entity_type text DEFAULT NULL::text, p_entity_id text DEFAULT NULL::text, p_before_data jsonb DEFAULT NULL::jsonb, p_after_data jsonb DEFAULT NULL::jsonb, p_message text DEFAULT NULL::text, p_error_detail text DEFAULT NULL::text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_profile public.profiles%rowtype; v_id uuid; v_severity text; v_status text;
begin
  if auth.uid() is null or p_user_id is null or p_user_id <> auth.uid() then
    raise exception 'FutonHUB blackbox: usuario autenticado no coincide con p_user_id';
  end if;
  select * into v_profile from public.profiles where id = auth.uid() and active = true limit 1;
  if v_profile.id is null then raise exception 'FutonHUB blackbox: usuario no valido o inactivo para audit_log'; end if;
  if v_profile.role not in ('admin', 'worker') then raise exception 'FutonHUB blackbox: rol no autorizado para audit_log'; end if;
  if p_user_email is not null and lower(p_user_email) <> lower(v_profile.email) then
    raise exception 'FutonHUB blackbox: email no coincide con el perfil autenticado';
  end if;
  v_severity := upper(coalesce(nullif(p_severity, ''), 'INFO'));
  if v_severity not in ('INFO', 'WARNING', 'ERROR', 'CRITICAL') then v_severity := 'INFO'; end if;
  v_status := upper(coalesce(nullif(p_status, ''), 'OK'));
  insert into public.audit_logs(operation_id,user_id,user_email,role,device_id,machine_name,module,action,entity_type,entity_id,severity,status,before_data,after_data,message,error_detail)
  values (p_operation_id,v_profile.id,v_profile.email,v_profile.role,p_device_id,p_machine_name,p_module,p_action,p_entity_type,p_entity_id,v_severity,v_status,p_before_data,p_after_data,p_message,p_error_detail)
  returning id into v_id;
  return jsonb_build_object('id', v_id,'operation_id', p_operation_id,'user_id', v_profile.id,'user_email', v_profile.email,'role', v_profile.role,'module', p_module,'action', p_action,'status', v_status,'severity', v_severity);
end;
$function$;

CREATE OR REPLACE FUNCTION public.futonhub_write_operation_snapshot(p_operation_id text, p_user_id uuid, p_module text, p_action text, p_entity_type text, p_entity_id text, p_before_data jsonb, p_reason text DEFAULT NULL::text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare v_profile public.profiles%rowtype; v_id uuid;
begin
  if auth.uid() is null or p_user_id is null or p_user_id <> auth.uid() then
    raise exception 'FutonHUB blackbox: usuario autenticado no coincide con p_user_id';
  end if;
  select * into v_profile from public.profiles where id = auth.uid() and active = true limit 1;
  if v_profile.id is null then raise exception 'FutonHUB blackbox: usuario no valido o inactivo para operation_snapshot'; end if;
  if v_profile.role not in ('admin', 'worker') then raise exception 'FutonHUB blackbox: rol no autorizado para operation_snapshot'; end if;
  insert into public.operation_snapshots(operation_id,user_id,module,action,entity_type,entity_id,before_data,reason)
  values (p_operation_id,v_profile.id,p_module,p_action,p_entity_type,p_entity_id,coalesce(p_before_data, '{}'::jsonb),p_reason)
  returning id into v_id;
  return jsonb_build_object('id', v_id,'operation_id', p_operation_id,'user_id', v_profile.id,'role', v_profile.role,'module', p_module,'action', p_action,'entity_type', p_entity_type,'entity_id', p_entity_id);
end;
$function$;

-- ===== VISTAS (sin security_invoker: reloptions NULL en vivo) =====
CREATE VIEW public.v_inventory_component_search AS
 WITH base AS (
  SELECT c.id AS relation_id, c.parent_item_code, c.component_item_code, c.quantity, c.relation_type, c.notes, c.created_at, c.created_by,
   p.item_id AS parent_item_id, p.name AS parent_name, p.heca_reference AS parent_heca_reference, p.hub_item_code AS parent_hub_item_code,
   p.woo_id AS parent_woo_id, p.woo_sku AS parent_woo_sku, p.woo_name AS parent_woo_name, p.woo_link_status AS parent_woo_link_status,
   i.item_id AS component_item_id_int, i.name AS component_name, i.heca_reference AS component_heca_reference, i.hub_item_code AS component_hub_item_code,
   i.woo_id AS component_woo_id, i.woo_sku AS component_woo_sku, i.woo_name AS component_woo_name, i.woo_link_status AS component_woo_link_status
  FROM inventory_item_components c
  LEFT JOIN inventory_items p ON COALESCE(p.hub_item_code, p.heca_reference, p.item_id::text) = c.parent_item_code
  LEFT JOIN inventory_items i ON COALESCE(i.hub_item_code, i.heca_reference, i.item_id::text) = c.component_item_code
 ), tokens AS (
  SELECT b.*, b.parent_item_code AS search_token, 'parent_code'::text AS token_type FROM base b WHERE NULLIF(TRIM(BOTH FROM b.parent_item_code), '') IS NOT NULL
  UNION ALL
  SELECT b.*, b.component_item_code, 'component_code'::text FROM base b WHERE NULLIF(TRIM(BOTH FROM b.component_item_code), '') IS NOT NULL
  UNION ALL
  SELECT b.*, TRIM(BOTH FROM token.token), 'woo_sku_token'::text FROM base b
   CROSS JOIN LATERAL regexp_split_to_table(COALESCE(b.parent_woo_sku, ''), '\\|') token(token) WHERE NULLIF(TRIM(BOTH FROM token.token), '') IS NOT NULL
 )
 SELECT relation_id, parent_item_code, parent_item_id, parent_name, parent_heca_reference, parent_hub_item_code, parent_woo_id AS woo_id,
  parent_woo_sku AS woo_sku, parent_woo_name AS woo_name, parent_woo_link_status AS woo_link_status, component_item_code, component_item_id_int,
  component_name, component_heca_reference, component_hub_item_code, component_woo_id, component_woo_sku, component_woo_name, component_woo_link_status,
  quantity, relation_type, notes, search_token, token_type, created_at, created_by FROM tokens;

CREATE VIEW public.v_inventory_hub_search_exact AS
 SELECT lower(TRIM(BOTH FROM i.hub_item_code)) AS search_token_norm, TRIM(BOTH FROM i.hub_item_code) AS search_token, 'direct_hub_item_code'::text AS token_type,
  i.item_id AS result_item_id, i.hub_item_code AS result_item_code, i.item_record_type AS result_record_type, i.name AS result_name, i.family AS result_family,
  i.subgroup AS result_subgroup, i.woo_id AS result_woo_id, i.woo_parent_id AS result_woo_parent_id, i.woo_sku AS result_woo_sku,
  NULL::text AS related_item_code, NULL::text AS related_name, NULL::numeric AS relation_quantity, NULL::text AS relation_type
  FROM inventory_items i WHERE NULLIF(TRIM(BOTH FROM COALESCE(i.hub_item_code, '')), '') IS NOT NULL
 UNION ALL
 SELECT lower(TRIM(BOTH FROM i.item_id::text)), TRIM(BOTH FROM i.item_id::text), 'direct_item_id'::text, i.item_id, i.hub_item_code, i.item_record_type, i.name, i.family, i.subgroup,
  i.woo_id, i.woo_parent_id, i.woo_sku, NULL::text, NULL::text, NULL::numeric, NULL::text FROM inventory_items i WHERE i.item_id IS NOT NULL
 UNION ALL
 SELECT lower(TRIM(BOTH FROM i.heca_reference)), TRIM(BOTH FROM i.heca_reference), 'direct_heca_reference'::text, i.item_id, i.hub_item_code, i.item_record_type, i.name, i.family, i.subgroup,
  i.woo_id, i.woo_parent_id, i.woo_sku, NULL::text, NULL::text, NULL::numeric, NULL::text FROM inventory_items i WHERE NULLIF(TRIM(BOTH FROM COALESCE(i.heca_reference, '')), '') IS NOT NULL
 UNION ALL
 SELECT lower(TRIM(BOTH FROM i.woo_sku)), TRIM(BOTH FROM i.woo_sku), 'direct_woo_sku_full'::text, i.item_id, i.hub_item_code, i.item_record_type, i.name, i.family, i.subgroup,
  i.woo_id, i.woo_parent_id, i.woo_sku, NULL::text, NULL::text, NULL::numeric, NULL::text FROM inventory_items i WHERE NULLIF(TRIM(BOTH FROM COALESCE(i.woo_sku, '')), '') IS NOT NULL
 UNION ALL
 SELECT lower(TRIM(BOTH FROM c.component_item_code)), TRIM(BOTH FROM c.component_item_code),
  CASE WHEN c.relation_type = 'alias' THEN 'alias_base_match'::text ELSE 'component_match'::text END,
  p.item_id, c.parent_item_code, p.item_record_type, COALESCE(p.name, c.parent_name), p.family, p.subgroup, COALESCE(p.woo_id, c.woo_id), p.woo_parent_id, COALESCE(p.woo_sku, c.woo_sku),
  c.component_item_code, COALESCE(ci.name, c.component_name), c.quantity, c.relation_type
  FROM inventory_item_components c
  LEFT JOIN inventory_items p ON p.hub_item_code = c.parent_item_code OR p.heca_reference = c.parent_item_code OR p.item_id::text = c.parent_item_code
  LEFT JOIN inventory_items ci ON ci.hub_item_code = c.component_item_code OR ci.heca_reference = c.component_item_code OR ci.item_id::text = c.component_item_code
  WHERE NULLIF(TRIM(BOTH FROM COALESCE(c.component_item_code, '')), '') IS NOT NULL
 UNION ALL
 SELECT lower(TRIM(BOTH FROM c.parent_item_code)), TRIM(BOTH FROM c.parent_item_code), 'relation_parent_match'::text,
  p.item_id, c.parent_item_code, p.item_record_type, COALESCE(p.name, c.parent_name), p.family, p.subgroup, COALESCE(p.woo_id, c.woo_id), p.woo_parent_id, COALESCE(p.woo_sku, c.woo_sku),
  c.component_item_code, COALESCE(ci.name, c.component_name), c.quantity, c.relation_type
  FROM inventory_item_components c
  LEFT JOIN inventory_items p ON p.hub_item_code = c.parent_item_code OR p.heca_reference = c.parent_item_code OR p.item_id::text = c.parent_item_code
  LEFT JOIN inventory_items ci ON ci.hub_item_code = c.component_item_code OR ci.heca_reference = c.component_item_code OR ci.item_id::text = c.component_item_code
  WHERE NULLIF(TRIM(BOTH FROM COALESCE(c.parent_item_code, '')), '') IS NOT NULL;

CREATE VIEW public.v_inventory_hub_search_ranked AS
 WITH ranked AS (
  SELECT s.search_token_norm, s.search_token, s.token_type, s.result_item_id, s.result_item_code, s.result_record_type, s.result_name, s.result_family, s.result_subgroup,
   s.result_woo_id, s.result_woo_parent_id, s.result_woo_sku, s.related_item_code, s.related_name, s.relation_quantity, s.relation_type,
   CASE WHEN s.token_type='direct_hub_item_code' THEN 10 WHEN s.token_type='direct_heca_reference' THEN 20 WHEN s.token_type='direct_item_id' THEN 25
    WHEN s.token_type='direct_woo_sku_full' THEN 30 WHEN s.token_type='relation_parent_match' THEN 35 WHEN s.token_type='alias_parent_match' THEN 40
    WHEN s.token_type='alias_base_match' THEN 50 WHEN s.token_type='component_match' THEN 60 WHEN s.token_type='woo_sku_token' THEN 70 ELSE 999 END AS match_priority,
   row_number() OVER (PARTITION BY lower(TRIM(BOTH FROM COALESCE(s.search_token_norm, ''))), s.result_item_id, COALESCE(s.related_item_code, ''), COALESCE(s.relation_type, ''), COALESCE(s.relation_quantity::text, '')
    ORDER BY (CASE WHEN s.token_type='direct_hub_item_code' THEN 10 WHEN s.token_type='direct_heca_reference' THEN 20 WHEN s.token_type='direct_item_id' THEN 25
    WHEN s.token_type='direct_woo_sku_full' THEN 30 WHEN s.token_type='relation_parent_match' THEN 35 WHEN s.token_type='alias_parent_match' THEN 40
    WHEN s.token_type='alias_base_match' THEN 50 WHEN s.token_type='component_match' THEN 60 WHEN s.token_type='woo_sku_token' THEN 70 ELSE 999 END), s.result_item_code, s.related_item_code) AS rn
  FROM v_inventory_hub_search_exact s)
 SELECT search_token_norm, search_token, result_item_id, result_item_code, result_record_type, result_name, result_family, result_subgroup, result_woo_id,
  result_woo_parent_id, result_woo_sku, related_item_code, related_name, relation_quantity, relation_type, token_type AS best_token_type, match_priority
 FROM ranked WHERE rn = 1;

-- ===== RLS =====
DO $$ DECLARE t text; BEGIN
 FOR t IN SELECT unnest(ARRAY['audit_logs','business_constants','devices','entity_locks','heca_stock','inventory_change_history','inventory_item_components','inventory_items','inventory_stock_reset_backups','notifications','operation_snapshots','price_change_proposals','product_variations','products','profiles','role_permissions','supplier_order_items','supplier_orders','supplier_prices','system_locks'])
 LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t); END LOOP; END $$;
-- inventory_item_components e inventory_stock_reset_backups: RLS activo y SIN politicas (vivo)

CREATE POLICY audit_logs_admin_select ON public.audit_logs FOR SELECT TO authenticated USING (current_user_role() = 'admin');
CREATE POLICY audit_logs_authenticated_insert ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY business_constants_admin_delete ON public.business_constants FOR DELETE TO authenticated USING (is_admin());
CREATE POLICY business_constants_authenticated_read ON public.business_constants FOR SELECT TO authenticated USING (true);
CREATE POLICY business_constants_worker_admin_insert ON public.business_constants FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY business_constants_worker_admin_update ON public.business_constants FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY devices_insert_self ON public.devices FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()) OR is_admin());
CREATE POLICY devices_self_or_admin ON public.devices FOR SELECT TO authenticated USING ((user_id = auth.uid()) OR is_admin());
CREATE POLICY entity_locks_authenticated_read ON public.entity_locks FOR SELECT TO authenticated USING (true);
CREATE POLICY entity_locks_authenticated_write ON public.entity_locks FOR INSERT TO authenticated WITH CHECK ((locked_by = auth.uid()) OR is_admin());
CREATE POLICY heca_stock_authenticated_read ON public.heca_stock FOR SELECT TO authenticated USING (true);
CREATE POLICY heca_stock_worker_admin_insert ON public.heca_stock FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY heca_stock_worker_admin_update ON public.heca_stock FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY inventory_change_history_admin_insert ON public.inventory_change_history FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY inventory_change_history_authenticated_read ON public.inventory_change_history FOR SELECT TO authenticated USING (true);
CREATE POLICY inventory_authenticated_read ON public.inventory_items FOR SELECT TO authenticated USING (true);
CREATE POLICY inventory_worker_admin_insert ON public.inventory_items FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY inventory_worker_admin_update ON public.inventory_items FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY notifications_insert_admin ON public.notifications FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY notifications_own_or_admin ON public.notifications FOR SELECT TO authenticated USING ((user_id = auth.uid()) OR (target_role = current_user_role()) OR is_admin());
CREATE POLICY operation_snapshots_admin_select ON public.operation_snapshots FOR SELECT TO authenticated USING (current_user_role() = 'admin');
CREATE POLICY operation_snapshots_authenticated_insert ON public.operation_snapshots FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY price_change_proposals_authenticated_select ON public.price_change_proposals FOR SELECT TO authenticated USING (true);
CREATE POLICY price_proposals_authenticated_read ON public.price_change_proposals FOR SELECT TO authenticated USING (true);
CREATE POLICY price_proposals_worker_admin_insert ON public.price_change_proposals FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY price_proposals_worker_admin_update ON public.price_change_proposals FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY variations_admin_write ON public.product_variations FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY variations_authenticated_read ON public.product_variations FOR SELECT TO authenticated USING (true);
CREATE POLICY products_admin_write ON public.products FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY products_authenticated_read ON public.products FOR SELECT TO authenticated USING (true);
CREATE POLICY profiles_admin_all ON public.profiles FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY profiles_select_self_or_admin ON public.profiles FOR SELECT TO authenticated USING ((id = auth.uid()) OR is_admin());
CREATE POLICY role_permissions_read_authenticated ON public.role_permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY supplier_order_items_authenticated_read ON public.supplier_order_items FOR SELECT TO authenticated USING (true);
CREATE POLICY supplier_order_items_worker_admin_insert ON public.supplier_order_items FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY supplier_order_items_worker_admin_update ON public.supplier_order_items FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY supplier_orders_authenticated_read ON public.supplier_orders FOR SELECT TO authenticated USING (true);
CREATE POLICY supplier_orders_worker_admin_insert ON public.supplier_orders FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY supplier_orders_worker_admin_update ON public.supplier_orders FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY supplier_prices_authenticated_read ON public.supplier_prices FOR SELECT TO authenticated USING (true);
CREATE POLICY supplier_prices_worker_admin_insert ON public.supplier_prices FOR INSERT TO authenticated WITH CHECK (is_worker_or_admin());
CREATE POLICY supplier_prices_worker_admin_update ON public.supplier_prices FOR UPDATE TO authenticated USING (is_worker_or_admin()) WITH CHECK (is_worker_or_admin());
CREATE POLICY locks_admin_all ON public.system_locks FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY locks_authenticated_read ON public.system_locks FOR SELECT TO authenticated USING (true);

-- ===== GRANTS (vivo: ALL a anon/authenticated/service_role en todas las tablas y vistas; EXECUTE segun routine_privileges) =====
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
-- futonhub_acquire/release/write_*: solo authenticated + service_role (sin PUBLIC ni anon)
REVOKE ALL ON FUNCTION public.futonhub_acquire_system_lock(text,uuid,text,text,integer), public.futonhub_release_system_lock(text,uuid,text),
 public.futonhub_write_audit_log(text,uuid,text,text,uuid,text,text,text,text,text,text,text,jsonb,jsonb,text,text),
 public.futonhub_write_operation_snapshot(text,uuid,text,text,text,text,jsonb,text),
 public.futonhub_read_audit_logs(uuid,integer), public.futonhub_read_operation_snapshots(uuid,integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.futonhub_acquire_system_lock(text,uuid,text,text,integer), public.futonhub_release_system_lock(text,uuid,text),
 public.futonhub_write_audit_log(text,uuid,text,text,uuid,text,text,text,text,text,text,text,jsonb,jsonb,text,text),
 public.futonhub_write_operation_snapshot(text,uuid,text,text,text,text,jsonb,text) TO authenticated, service_role;
-- read_audit_logs / read_operation_snapshots: anon + authenticated + service_role (sin PUBLIC)
GRANT EXECUTE ON FUNCTION public.futonhub_read_audit_logs(uuid,integer), public.futonhub_read_operation_snapshots(uuid,integer) TO anon, authenticated, service_role;
-- resto de funciones: PUBLIC + anon + authenticated + service_role (por defecto)
